import Head from "next/head";
import styles from "../styles/Products.module.css";

import ProductsListDivider from "../components/ProductsListDivider/ProductsListDivider";
import PersonalProtectionItems from "../components/ItemsCollection/PersonalProtectionItems";
import FireFightingItems from "../components/ItemsCollection/FireFightingItems";
import WorkwearItems from "../components/ItemsCollection/WorkwearItems";

import personalProtDivider from "../public/images/glove-wide.jpg";
import fireFightingDivider from "../public/images/firefighters-articles.jpg";
import workwearDivider from "../public/images/workwear-card.jpg";

export default function Products() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
          crossOrigin="anonymous"
        />
      </Head>

      <ProductsListDivider
        image={personalProtDivider}
        alt="Work gloves photo"
        text="środki ochrony indywidualnej"
      />
      <PersonalProtectionItems />

      <ProductsListDivider
        image={fireFightingDivider}
        alt="Firefighters with firehose"
        text="sprzęt przeciwpożarowy"
      />
      <FireFightingItems />

      <ProductsListDivider
        image={workwearDivider}
        alt=""
        text="odzież robocze"
      />
      <WorkwearItems />
    </>
  );
}
